### ISSUE TITLE
Error when adding values to a MTM relation combobox

### ISSUE THREAD

**Issue by Timonwatteny** [nambu-ch/pimcore-relation-select-fields#5]
The layout issues has been solved, for which I must thank you. 

But after adding the MTM relation combobox and trying to add a value following error is being shown: 
![Screenshot 2021-11-23 at 10 27 53](https://user-images.githubusercontent.com/31765954/143000452-404d254e-3998-44a4-b2af-f50e867840a1.png)

`Timestamp: Tue Nov 23 2021 10:30:37 GMT+0100 (Central European Standard Time)
Status: 500 | 
URL: /admin/object/save?task=publish
Method: PUT
Message: Warning: Trying to access array offset on value of type null`

**Comment by dominikschnieper** [comment]
This issue has been resolved in V2.0.7, thanks for your patience and the reporting.
