### ISSUE TITLE
Filter by relation in grid doesn't work

### ISSUE THREAD

**Issue by FragarachBugs** [nambu-ch/pimcore-relation-select-fields#7]
If you want to filter by relation to any column which works with 'select' - it doesn't work.  Filter result is always empty
<img width="1107" alt="Screenshot 2022-08-12 at 12 42 59" src="https://user-images.githubusercontent.com/37364725/184338911-39557192-b58f-43bd-97cb-9c6ea779e5c5.png">
<img width="1107" alt="Screenshot 2022-08-12 at 12 43 18" src="https://user-images.githubusercontent.com/37364725/184338923-e488b038-bdba-4587-b026-f28f006c7cbd.png">
<img width="1107" alt="Screenshot 2022-08-12 at 12 43 25" src="https://user-images.githubusercontent.com/37364725/184338926-64cadb8d-2b7b-4a44-afd7-29eea2950fc6.png">

**Comment by dominikschnieper** [comment]
Thank you for this input. It is fixed with the new version 2.1.1.
